export type CampusNodeType =
	| "building"
	| "entrance"
	| "intersection"
	| "crosswalk"
	| "metro"
	| "tunnel";

export interface CampusNode {
	id: string;
	label: string;
	type: CampusNodeType;
	x: number;
	y: number;
	buildingCode?: string;
	address?: string;
	tags?: string[];
}

export interface CampusEdge {
	id: string;
	from: string;
	to: string;
	distance: number;
	indoor?: boolean;
	accessible?: boolean;
	tags?: string[];
	instruction?: string;
	reverseInstruction?: string;
}

export interface BuildingIndexEntry {
	id: string;
	code: string;
	name: string;
	address: string;
	entranceIds: string[];
}

export const sgwNodes: CampusNode[] = [
	// Intersections / street anchors
	{
		id: "guy_sherbrooke",
		label: "Guy / Sherbrooke",
		type: "intersection",
		x: 20,
		y: 8,
		tags: ["outdoor"],
	},
	{
		id: "mackay_sherbrooke",
		label: "Mackay / Sherbrooke",
		type: "intersection",
		x: 56,
		y: 8,
		tags: ["outdoor"],
	},
	{
		id: "bishop_sherbrooke",
		label: "Bishop / Sherbrooke",
		type: "intersection",
		x: 76,
		y: 8,
		tags: ["outdoor"],
	},

	{
		id: "guy_lincoln",
		label: "Guy / Lincoln",
		type: "intersection",
		x: 20,
		y: 18,
		tags: ["outdoor"],
	},
	{
		id: "mackay_lincoln",
		label: "Mackay / Lincoln",
		type: "intersection",
		x: 56,
		y: 18,
		tags: ["outdoor"],
	},
	{
		id: "bishop_lincoln",
		label: "Bishop / Lincoln",
		type: "intersection",
		x: 76,
		y: 18,
		tags: ["outdoor"],
	},

	{
		id: "guy_demaisonneuve",
		label: "Guy / De Maisonneuve",
		type: "intersection",
		x: 20,
		y: 30,
		tags: ["outdoor", "major"],
	},
	{
		id: "stmathieu_demaisonneuve",
		label: "St-Mathieu / De Maisonneuve",
		type: "intersection",
		x: 30,
		y: 30,
		tags: ["outdoor"],
	},
	{
		id: "mackay_demaisonneuve",
		label: "Mackay / De Maisonneuve",
		type: "intersection",
		x: 56,
		y: 30,
		tags: ["outdoor", "major"],
	},
	{
		id: "bishop_demaisonneuve",
		label: "Bishop / De Maisonneuve",
		type: "intersection",
		x: 76,
		y: 30,
		tags: ["outdoor"],
	},

	{
		id: "guy_stecatherine",
		label: "Guy / Sainte-Catherine",
		type: "intersection",
		x: 20,
		y: 46,
		tags: ["outdoor", "major"],
	},
	{
		id: "stmathieu_stecatherine",
		label: "St-Mathieu / Sainte-Catherine",
		type: "intersection",
		x: 30,
		y: 46,
		tags: ["outdoor"],
	},
	{
		id: "mackay_stecatherine",
		label: "Mackay / Sainte-Catherine",
		type: "intersection",
		x: 56,
		y: 46,
		tags: ["outdoor"],
	},
	{
		id: "bishop_stecatherine",
		label: "Bishop / Sainte-Catherine",
		type: "intersection",
		x: 76,
		y: 46,
		tags: ["outdoor"],
	},

	{
		id: "guy_renelevesque",
		label: "Guy / René-Lévesque",
		type: "intersection",
		x: 20,
		y: 70,
		tags: ["outdoor"],
	},
	{
		id: "stmathieu_renelevesque",
		label: "St-Mathieu / René-Lévesque",
		type: "intersection",
		x: 30,
		y: 70,
		tags: ["outdoor"],
	},
	{
		id: "bishop_renelevesque",
		label: "Bishop / René-Lévesque",
		type: "intersection",
		x: 76,
		y: 70,
		tags: ["outdoor"],
	},

	// Transit
	{
		id: "guy_concordia_metro",
		label: "Guy-Concordia Metro",
		type: "metro",
		x: 14,
		y: 30,
		tags: ["transit", "popular"],
	},
	{
		id: "lucien_lallier_metro",
		label: "Lucien-L'Allier Metro",
		type: "metro",
		x: 86,
		y: 72,
		tags: ["transit"],
	},

	// Major buildings
	{
		id: "MB",
		label: "John Molson Building",
		type: "building",
		x: 18,
		y: 35,
		buildingCode: "MB",
		address: "1450 Guy St.",
		tags: ["indoor", "popular", "business"],
	},
	{
		id: "H",
		label: "Henry F. Hall Building",
		type: "building",
		x: 36,
		y: 34,
		buildingCode: "H",
		address: "1455 De Maisonneuve Blvd. W.",
		tags: ["indoor", "popular", "academic"],
	},
	{
		id: "GM",
		label: "Guy-De Maisonneuve Building",
		type: "building",
		x: 48,
		y: 33,
		buildingCode: "GM",
		address: "1550 De Maisonneuve Blvd. W.",
		tags: ["indoor", "academic"],
	},
	{
		id: "LS",
		label: "Learning Square",
		type: "building",
		x: 40,
		y: 28,
		buildingCode: "LS",
		address: "1535 De Maisonneuve Blvd. W.",
		tags: ["indoor", "student-services", "academic"],
	},
	{
		id: "LB",
		label: "J.W. McConnell Building",
		type: "building",
		x: 67,
		y: 34,
		buildingCode: "LB",
		address: "1400 De Maisonneuve Blvd. W.",
		tags: ["indoor", "popular", "library"],
	},
	{
		id: "EV",
		label: "Engineering, Computer Science and Visual Arts Integrated Complex",
		type: "building",
		x: 57,
		y: 48,
		buildingCode: "EV",
		address: "1515 Ste-Catherine St. W.",
		tags: ["indoor", "popular", "engineering", "computer-science"],
	},
	{
		id: "FB",
		label: "Faubourg Building",
		type: "building",
		x: 18,
		y: 43,
		buildingCode: "FB",
		address: "1250 Guy St.",
		tags: ["indoor", "academic"],
	},
	{
		id: "FG",
		label: "Faubourg Ste-Catherine Building",
		type: "building",
		x: 8,
		y: 52,
		buildingCode: "FG",
		address: "1610 Ste-Catherine St. W.",
		tags: ["indoor", "academic", "retail"],
	},
	{
		id: "GN",
		label: "Grey Nuns Building",
		type: "building",
		x: 18,
		y: 62,
		buildingCode: "GN",
		address: "1190 Guy St.",
		tags: ["indoor", "residence", "historic"],
	},
	{
		id: "GA",
		label: "Grey Nuns Annex",
		type: "building",
		x: 28,
		y: 58,
		buildingCode: "GA",
		address: "1211-1215 St-Mathieu St.",
		tags: ["indoor", "academic"],
	},
	{
		id: "VA",
		label: "Visual Arts Building",
		type: "building",
		x: 82,
		y: 62,
		buildingCode: "VA",
		address: "1395 René-Lévesque Blvd. W.",
		tags: ["indoor", "fine-arts"],
	},

	// Secondary academic / annex anchors
	{
		id: "TD",
		label: "Toronto-Dominion Building",
		type: "building",
		x: 18,
		y: 39,
		buildingCode: "TD",
		address: "1410 Guy St.",
		tags: ["indoor"],
	},
	{
		id: "ER",
		label: "ER Building",
		type: "building",
		x: 24,
		y: 18,
		buildingCode: "ER",
		address: "2155 Guy St.",
		tags: ["indoor"],
	},
	{
		id: "GS",
		label: "GS Building",
		type: "building",
		x: 30,
		y: 10,
		buildingCode: "GS",
		address: "1538 Sherbrooke St. W.",
		tags: ["indoor"],
	},
	{
		id: "SB",
		label: "Samuel Bronfman Building",
		type: "building",
		x: 42,
		y: 4,
		buildingCode: "SB",
		address: "1590 Dr. Penfield",
		tags: ["indoor", "fine-arts"],
	},
	{
		id: "B",
		label: "B Annex",
		type: "building",
		x: 78,
		y: 8,
		buildingCode: "B",
		address: "2160 Bishop St.",
		tags: ["indoor"],
	},
	{
		id: "CI",
		label: "CI Annex",
		type: "building",
		x: 66,
		y: 8,
		buildingCode: "CI",
		address: "2149 Mackay St.",
		tags: ["indoor"],
	},
	{
		id: "D",
		label: "D Annex",
		type: "building",
		x: 78,
		y: 14,
		buildingCode: "D",
		address: "2140 Bishop St.",
		tags: ["indoor"],
	},
	{
		id: "EN",
		label: "EN Annex",
		type: "building",
		x: 54,
		y: 14,
		buildingCode: "EN",
		address: "2070 Mackay St.",
		tags: ["indoor"],
	},
	{
		id: "FA",
		label: "FA Annex",
		type: "building",
		x: 34,
		y: 20,
		buildingCode: "FA",
		address: "2060 Mackay St.",
		tags: ["indoor"],
	},
	{
		id: "CL",
		label: "CL Annex",
		type: "building",
		x: 6,
		y: 40,
		buildingCode: "CL",
		address: "1665 Ste-Catherine St. W.",
		tags: ["indoor"],
	},
	{
		id: "LD",
		label: "LD Building",
		type: "building",
		x: 67,
		y: 39,
		buildingCode: "LD",
		address: "1424 Bishop St.",
		tags: ["indoor"],
	},

	// Entrances
	{
		id: "MB_main_entrance",
		label: "MB main entrance",
		type: "entrance",
		x: 19,
		y: 31,
		tags: ["entrance", "accessible"],
	},
	{
		id: "H_main_entrance",
		label: "Hall main entrance",
		type: "entrance",
		x: 36,
		y: 30,
		tags: ["entrance", "accessible"],
	},
	{
		id: "GM_main_entrance",
		label: "GM main entrance",
		type: "entrance",
		x: 48,
		y: 30,
		tags: ["entrance", "accessible"],
	},
	{
		id: "LS_main_entrance",
		label: "LS main entrance",
		type: "entrance",
		x: 40,
		y: 26,
		tags: ["entrance", "accessible"],
	},
	{
		id: "LB_main_entrance",
		label: "LB main entrance",
		type: "entrance",
		x: 67,
		y: 30,
		tags: ["entrance", "accessible"],
	},
	{
		id: "EV_main_entrance",
		label: "EV main entrance",
		type: "entrance",
		x: 57,
		y: 45,
		tags: ["entrance", "accessible"],
	},
	{
		id: "FB_main_entrance",
		label: "FB main entrance",
		type: "entrance",
		x: 19,
		y: 40,
		tags: ["entrance", "accessible"],
	},
	{
		id: "FG_main_entrance",
		label: "FG main entrance",
		type: "entrance",
		x: 9,
		y: 46,
		tags: ["entrance"],
	},
	{
		id: "GN_main_entrance",
		label: "GN main entrance",
		type: "entrance",
		x: 20,
		y: 58,
		tags: ["entrance"],
	},
	{
		id: "GA_main_entrance",
		label: "GA main entrance",
		type: "entrance",
		x: 28,
		y: 54,
		tags: ["entrance"],
	},
	{
		id: "VA_main_entrance",
		label: "VA main entrance",
		type: "entrance",
		x: 82,
		y: 68,
		tags: ["entrance"],
	},

	// Indoor connectors / tunnels
	{
		id: "H_MB_tunnel",
		label: "Hall-MB connector",
		type: "tunnel",
		x: 28,
		y: 33,
		tags: ["indoor", "tunnel", "accessible"],
	},
	{
		id: "H_GM_tunnel",
		label: "Hall-GM connector",
		type: "tunnel",
		x: 43,
		y: 33,
		tags: ["indoor", "tunnel", "accessible"],
	},
	{
		id: "GM_LB_tunnel",
		label: "GM-LB connector",
		type: "tunnel",
		x: 58,
		y: 33,
		tags: ["indoor", "tunnel", "accessible"],
	},
];

export const sgwEdges: CampusEdge[] = [
	// Metro access
	{
		id: "e_metro_1",
		from: "guy_concordia_metro",
		to: "guy_demaisonneuve",
		distance: 1,
		accessible: true,
		tags: ["outdoor", "transit"],
		instruction: "Exit Guy-Concordia metro toward De Maisonneuve.",
	},

	// De Maisonneuve corridor
	{
		id: "e_dm_1",
		from: "guy_demaisonneuve",
		to: "stmathieu_demaisonneuve",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk east along De Maisonneuve toward St-Mathieu.",
		reverseInstruction: "Walk west along De Maisonneuve toward Guy.",
	},
	{
		id: "e_dm_2",
		from: "stmathieu_demaisonneuve",
		to: "mackay_demaisonneuve",
		distance: 4,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue east along De Maisonneuve toward Mackay.",
		reverseInstruction: "Walk west along De Maisonneuve toward St-Mathieu.",
	},
	{
		id: "e_dm_3",
		from: "mackay_demaisonneuve",
		to: "bishop_demaisonneuve",
		distance: 3,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue east along De Maisonneuve toward Bishop.",
		reverseInstruction: "Walk west along De Maisonneuve toward Mackay.",
	},

	// Sainte-Catherine corridor
	{
		id: "e_sc_1",
		from: "guy_stecatherine",
		to: "stmathieu_stecatherine",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk east along Sainte-Catherine toward St-Mathieu.",
		reverseInstruction: "Walk west along Sainte-Catherine toward Guy.",
	},
	{
		id: "e_sc_2",
		from: "stmathieu_stecatherine",
		to: "mackay_stecatherine",
		distance: 4,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue east along Sainte-Catherine toward Mackay.",
		reverseInstruction: "Walk west along Sainte-Catherine toward St-Mathieu.",
	},
	{
		id: "e_sc_3",
		from: "mackay_stecatherine",
		to: "bishop_stecatherine",
		distance: 3,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue east along Sainte-Catherine toward Bishop.",
		reverseInstruction: "Walk west along Sainte-Catherine toward Mackay.",
	},

	// Sherbrooke corridor
	{
		id: "e_sh_1",
		from: "guy_sherbrooke",
		to: "mackay_sherbrooke",
		distance: 5,
		accessible: true,
		tags: ["outdoor"],
		instruction: "Walk east along Sherbrooke toward Mackay.",
	},
	{
		id: "e_sh_2",
		from: "mackay_sherbrooke",
		to: "bishop_sherbrooke",
		distance: 3,
		accessible: true,
		tags: ["outdoor"],
		instruction: "Continue east along Sherbrooke toward Bishop.",
	},

	// René-Lévesque corridor
	{
		id: "e_rl_1",
		from: "guy_renelevesque",
		to: "stmathieu_renelevesque",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk east along René-Lévesque toward St-Mathieu.",
		reverseInstruction: "Walk west along René-Lévesque toward Guy.",
	},
	{
		id: "e_rl_2",
		from: "stmathieu_renelevesque",
		to: "bishop_renelevesque",
		distance: 6,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue east along René-Lévesque toward Bishop.",
		reverseInstruction: "Walk west along René-Lévesque toward St-Mathieu.",
	},

	// Guy vertical corridor
	{
		id: "e_guy_1",
		from: "guy_sherbrooke",
		to: "guy_lincoln",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk south on Guy toward Lincoln.",
		reverseInstruction: "Walk north on Guy toward Sherbrooke.",
	},
	{
		id: "e_guy_2",
		from: "guy_lincoln",
		to: "guy_demaisonneuve",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Guy toward De Maisonneuve.",
		reverseInstruction: "Walk north on Guy toward Lincoln.",
	},
	{
		id: "e_guy_3",
		from: "guy_demaisonneuve",
		to: "guy_stecatherine",
		distance: 3,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Guy toward Sainte-Catherine.",
		reverseInstruction: "Walk north on Guy toward De Maisonneuve.",
	},
	{
		id: "e_guy_4",
		from: "guy_stecatherine",
		to: "guy_renelevesque",
		distance: 5,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Guy toward René-Lévesque.",
		reverseInstruction: "Walk north on Guy toward Sainte-Catherine.",
	},

	// St-Mathieu vertical corridor
	{
		id: "e_sm_1",
		from: "stmathieu_demaisonneuve",
		to: "stmathieu_stecatherine",
		distance: 3,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk south on St-Mathieu toward Sainte-Catherine.",
		reverseInstruction: "Walk north on St-Mathieu toward De Maisonneuve.",
	},
	{
		id: "e_sm_2",
		from: "stmathieu_stecatherine",
		to: "stmathieu_renelevesque",
		distance: 5,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on St-Mathieu toward René-Lévesque.",
		reverseInstruction: "Walk north on St-Mathieu toward Sainte-Catherine.",
	},

	// Mackay vertical corridor
	{
		id: "e_mk_1",
		from: "mackay_sherbrooke",
		to: "mackay_lincoln",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk south on Mackay toward Lincoln.",
		reverseInstruction: "Walk north on Mackay toward Sherbrooke.",
	},
	{
		id: "e_mk_2",
		from: "mackay_lincoln",
		to: "mackay_demaisonneuve",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Mackay toward De Maisonneuve.",
		reverseInstruction: "Walk north on Mackay toward Lincoln.",
	},
	{
		id: "e_mk_3",
		from: "mackay_demaisonneuve",
		to: "mackay_stecatherine",
		distance: 3,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Mackay toward Sainte-Catherine.",
		reverseInstruction: "Walk north on Mackay toward De Maisonneuve.",
	},

	// Bishop vertical corridor
	{
		id: "e_bp_1",
		from: "bishop_sherbrooke",
		to: "bishop_lincoln",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Walk south on Bishop toward Lincoln.",
		reverseInstruction: "Walk north on Bishop toward Sherbrooke.",
	},
	{
		id: "e_bp_2",
		from: "bishop_lincoln",
		to: "bishop_demaisonneuve",
		distance: 2,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Bishop toward De Maisonneuve.",
		reverseInstruction: "Walk north on Bishop toward Lincoln.",
	},
	{
		id: "e_bp_3",
		from: "bishop_demaisonneuve",
		to: "bishop_stecatherine",
		distance: 3,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Bishop toward Sainte-Catherine.",
		reverseInstruction: "Walk north on Bishop toward De Maisonneuve.",
	},
	{
		id: "e_bp_4",
		from: "bishop_stecatherine",
		to: "bishop_renelevesque",
		distance: 5,
		accessible: true,
		tags: ["outdoor", "street_segment"],
		instruction: "Continue south on Bishop toward René-Lévesque.",
		reverseInstruction: "Walk north on Bishop toward Sainte-Catherine.",
	},

	// Building entrances from streets
	{
		id: "e_mb_ent",
		from: "guy_demaisonneuve",
		to: "MB_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the John Molson entrance.",
	},
	{
		id: "e_h_ent",
		from: "stmathieu_demaisonneuve",
		to: "H_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the Hall entrance.",
	},
	{
		id: "e_gm_ent",
		from: "mackay_demaisonneuve",
		to: "GM_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the GM entrance.",
	},
	{
		id: "e_ls_ent",
		from: "stmathieu_demaisonneuve",
		to: "LS_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the Learning Square entrance.",
	},
	{
		id: "e_lb_ent",
		from: "bishop_demaisonneuve",
		to: "LB_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the Library entrance.",
	},
	{
		id: "e_ev_ent",
		from: "mackay_stecatherine",
		to: "EV_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the EV entrance.",
	},
	{
		id: "e_fb_ent",
		from: "guy_stecatherine",
		to: "FB_main_entrance",
		distance: 1,
		accessible: true,
		tags: ["entrance"],
		instruction: "Head to the Faubourg entrance.",
	},
	{
		id: "e_fg_ent",
		from: "stmathieu_stecatherine",
		to: "FG_main_entrance",
		distance: 2,
		accessible: false,
		tags: ["entrance"],
		instruction: "Head west to the Faubourg Ste-Catherine entrance.",
	},
	{
		id: "e_gn_ent",
		from: "guy_renelevesque",
		to: "GN_main_entrance",
		distance: 1,
		accessible: false,
		tags: ["entrance"],
		instruction: "Head to the Grey Nuns entrance.",
	},
	{
		id: "e_ga_ent",
		from: "stmathieu_stecatherine",
		to: "GA_main_entrance",
		distance: 2,
		accessible: false,
		tags: ["entrance"],
		instruction: "Head south toward the Grey Nuns Annex entrance.",
	},
	{
		id: "e_va_ent",
		from: "bishop_renelevesque",
		to: "VA_main_entrance",
		distance: 1,
		accessible: false,
		tags: ["entrance"],
		instruction: "Head to the Visual Arts entrance.",
	},

	// Enter buildings
	{
		id: "e_mb_in",
		from: "MB_main_entrance",
		to: "MB",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter the John Molson Building.",
	},
	{
		id: "e_h_in",
		from: "H_main_entrance",
		to: "H",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter the Hall Building.",
	},
	{
		id: "e_gm_in",
		from: "GM_main_entrance",
		to: "GM",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter the Guy-De Maisonneuve Building.",
	},
	{
		id: "e_ls_in",
		from: "LS_main_entrance",
		to: "LS",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter Learning Square.",
	},
	{
		id: "e_lb_in",
		from: "LB_main_entrance",
		to: "LB",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter the Library Building.",
	},
	{
		id: "e_ev_in",
		from: "EV_main_entrance",
		to: "EV",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter the EV Building.",
	},
	{
		id: "e_fb_in",
		from: "FB_main_entrance",
		to: "FB",
		distance: 1,
		indoor: true,
		accessible: true,
		instruction: "Enter the Faubourg Building.",
	},
	{
		id: "e_fg_in",
		from: "FG_main_entrance",
		to: "FG",
		distance: 1,
		indoor: true,
		instruction: "Enter the Faubourg Ste-Catherine Building.",
	},
	{
		id: "e_gn_in",
		from: "GN_main_entrance",
		to: "GN",
		distance: 1,
		indoor: true,
		instruction: "Enter the Grey Nuns Building.",
	},
	{
		id: "e_ga_in",
		from: "GA_main_entrance",
		to: "GA",
		distance: 1,
		indoor: true,
		instruction: "Enter the Grey Nuns Annex.",
	},
	{
		id: "e_va_in",
		from: "VA_main_entrance",
		to: "VA",
		distance: 1,
		indoor: true,
		instruction: "Enter the Visual Arts Building.",
	},

	// Indoor connectors
	{
		id: "e_tunnel_mb_h_1",
		from: "MB",
		to: "H_MB_tunnel",
		distance: 1,
		indoor: true,
		accessible: true,
		tags: ["connector", "tunnel"],
		instruction: "Follow the indoor connector toward Hall.",
		reverseInstruction: "Follow the indoor connector back toward MB.",
	},
	{
		id: "e_tunnel_mb_h_2",
		from: "H_MB_tunnel",
		to: "H",
		distance: 1,
		indoor: true,
		accessible: true,
		tags: ["connector", "tunnel"],
		instruction: "Continue through the connector into Hall.",
		reverseInstruction: "Continue through the connector back toward MB.",
	},
	{
		id: "e_tunnel_h_gm_1",
		from: "H",
		to: "H_GM_tunnel",
		distance: 1,
		indoor: true,
		accessible: true,
		tags: ["connector", "tunnel"],
		instruction: "Follow the indoor connector toward GM.",
		reverseInstruction: "Follow the indoor connector back toward Hall.",
	},
	{
		id: "e_tunnel_h_gm_2",
		from: "H_GM_tunnel",
		to: "GM",
		distance: 1,
		indoor: true,
		accessible: true,
		tags: ["connector", "tunnel"],
		instruction: "Continue through the connector into GM.",
		reverseInstruction: "Continue through the connector back toward Hall.",
	},
	{
		id: "e_tunnel_gm_lb_1",
		from: "GM",
		to: "GM_LB_tunnel",
		distance: 1,
		indoor: true,
		accessible: true,
		tags: ["connector", "tunnel"],
		instruction: "Follow the indoor connector toward the Library.",
		reverseInstruction: "Follow the indoor connector back toward GM.",
	},
	{
		id: "e_tunnel_gm_lb_2",
		from: "GM_LB_tunnel",
		to: "LB",
		distance: 1,
		indoor: true,
		accessible: true,
		tags: ["connector", "tunnel"],
		instruction: "Continue through the connector into the Library Building.",
		reverseInstruction: "Continue through the connector back toward GM.",
	},

	// Nearby outdoor shortcuts
	{
		id: "e_h_ev_outdoor",
		from: "H_main_entrance",
		to: "EV_main_entrance",
		distance: 4,
		accessible: true,
		tags: ["outdoor"],
		instruction: "Walk southeast from Hall toward the EV entrance.",
	},
	{
		id: "e_fb_gn_outdoor",
		from: "FB_main_entrance",
		to: "GN_main_entrance",
		distance: 4,
		accessible: false,
		tags: ["outdoor"],
		instruction: "Walk south from Faubourg toward Grey Nuns.",
	},
	{
		id: "e_gn_ga_outdoor",
		from: "GN_main_entrance",
		to: "GA_main_entrance",
		distance: 2,
		accessible: false,
		tags: ["outdoor"],
		instruction: "Walk northeast toward the Grey Nuns Annex.",
	},
];

// Make the graph bidirectional unless a route is intentionally one-way
export const sgwBidirectionalEdges: CampusEdge[] = sgwEdges.flatMap((edge) => [
	edge,
	{
		...edge,
		id: `${edge.id}_rev`,
		from: edge.to,
		to: edge.from,
		instruction: buildReverseInstruction(edge),
	},
]);

function getCampusNodeLabel(nodeId: string): string {
	return sgwNodes.find((node) => node.id === nodeId)?.label ?? nodeId;
}

function buildReverseInstruction(edge: CampusEdge): string | undefined {
	if (edge.reverseInstruction) {
		return edge.reverseInstruction;
	}

	const fromLabel = getCampusNodeLabel(edge.from);
	const toLabel = getCampusNodeLabel(edge.to);

	if (edge.id.endsWith("_in")) {
		return `Exit the ${toLabel} toward ${fromLabel}.`;
	}

	if (edge.id.endsWith("_ent")) {
		return `Continue from ${toLabel} toward ${fromLabel}.`;
	}

	return reverseInstruction(edge.instruction);
}

function reverseInstruction(instruction?: string): string | undefined {
	if (!instruction) return undefined;
	return `Continue toward ${instruction.toLowerCase().replace(/\.$/, "")}.`;
}

export const buildingIndex: Record<string, BuildingIndexEntry> = {
	MB: {
		id: "MB",
		code: "MB",
		name: "John Molson Building",
		address: "1450 Guy St.",
		entranceIds: ["MB_main_entrance"],
	},
	H: {
		id: "H",
		code: "H",
		name: "Henry F. Hall Building",
		address: "1455 De Maisonneuve Blvd. W.",
		entranceIds: ["H_main_entrance"],
	},
	GM: {
		id: "GM",
		code: "GM",
		name: "Guy-De Maisonneuve Building",
		address: "1550 De Maisonneuve Blvd. W.",
		entranceIds: ["GM_main_entrance"],
	},
	LS: {
		id: "LS",
		code: "LS",
		name: "Learning Square",
		address: "1535 De Maisonneuve Blvd. W.",
		entranceIds: ["LS_main_entrance"],
	},
	LB: {
		id: "LB",
		code: "LB",
		name: "J.W. McConnell Building",
		address: "1400 De Maisonneuve Blvd. W.",
		entranceIds: ["LB_main_entrance"],
	},
	EV: {
		id: "EV",
		code: "EV",
		name: "Engineering, Computer Science and Visual Arts Integrated Complex",
		address: "1515 Ste-Catherine St. W.",
		entranceIds: ["EV_main_entrance"],
	},
	FB: {
		id: "FB",
		code: "FB",
		name: "Faubourg Building",
		address: "1250 Guy St.",
		entranceIds: ["FB_main_entrance"],
	},
	FG: {
		id: "FG",
		code: "FG",
		name: "Faubourg Ste-Catherine Building",
		address: "1610 Ste-Catherine St. W.",
		entranceIds: ["FG_main_entrance"],
	},
	GN: {
		id: "GN",
		code: "GN",
		name: "Grey Nuns Building",
		address: "1190 Guy St.",
		entranceIds: ["GN_main_entrance"],
	},
	GA: {
		id: "GA",
		code: "GA",
		name: "Grey Nuns Annex",
		address: "1211-1215 St-Mathieu St.",
		entranceIds: ["GA_main_entrance"],
	},
	VA: {
		id: "VA",
		code: "VA",
		name: "Visual Arts Building",
		address: "1395 René-Lévesque Blvd. W.",
		entranceIds: ["VA_main_entrance"],
	},
	TD: {
		id: "TD",
		code: "TD",
		name: "Toronto-Dominion Building",
		address: "1410 Guy St.",
		entranceIds: [],
	},
	ER: {
		id: "ER",
		code: "ER",
		name: "ER Building",
		address: "2155 Guy St.",
		entranceIds: [],
	},
	GS: {
		id: "GS",
		code: "GS",
		name: "GS Building",
		address: "1538 Sherbrooke St. W.",
		entranceIds: [],
	},
	SB: {
		id: "SB",
		code: "SB",
		name: "Samuel Bronfman Building",
		address: "1590 Dr. Penfield",
		entranceIds: [],
	},
	B: {
		id: "B",
		code: "B",
		name: "B Annex",
		address: "2160 Bishop St.",
		entranceIds: [],
	},
	CI: {
		id: "CI",
		code: "CI",
		name: "CI Annex",
		address: "2149 Mackay St.",
		entranceIds: [],
	},
	D: {
		id: "D",
		code: "D",
		name: "D Annex",
		address: "2140 Bishop St.",
		entranceIds: [],
	},
	EN: {
		id: "EN",
		code: "EN",
		name: "EN Annex",
		address: "2070 Mackay St.",
		entranceIds: [],
	},
	FA: {
		id: "FA",
		code: "FA",
		name: "FA Annex",
		address: "2060 Mackay St.",
		entranceIds: [],
	},
	CL: {
		id: "CL",
		code: "CL",
		name: "CL Annex",
		address: "1665 Ste-Catherine St. W.",
		entranceIds: [],
	},
	LD: {
		id: "LD",
		code: "LD",
		name: "LD Building",
		address: "1424 Bishop St.",
		entranceIds: [],
	},
};

export const popularDestinations = [
	"guy_concordia_metro",
	"MB",
	"H",
	"GM",
	"LS",
	"LB",
	"EV",
	"FB",
	"FG",
	"GN",
	"GA",
	"VA",
];

export const nodeById = Object.fromEntries(
	sgwNodes.map((node) => [node.id, node]),
);
